version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install -U pip
    - pip install -U -r docs/requirements.txt
    - make docs
    - mv docs/_build $READTHEDOCS_OUTPUT
